/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;

/**
 *
 * @author Vian
 */
public class hometransaktor extends javax.swing.JFrame {

    /**
     * Creates new form hometransaktor
     */
    public hometransaktor() {
        initComponents();
    }

    public void addtLoginListener(ActionListener listener) {
        login.addActionListener(listener);
    }

    public void transaktor() {
        login.setVisible(false);
    }

    public void addPendaftaranMember(ActionListener listener) {
        daftar.addActionListener(listener);
    }

    public void addTransaksi(ActionListener listener) {
        transaktor.addActionListener(listener);
    }

    public void addtLogoutListener(ActionListener listener) {
        keluar.addActionListener(listener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login = new javax.swing.JButton();
        transaktor = new javax.swing.JButton();
        daftar = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        login.setText("masuk");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        transaktor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/transaksi.png"))); // NOI18N
        transaktor.setContentAreaFilled(false);
        transaktor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transaktorActionPerformed(evt);
            }
        });
        getContentPane().add(transaktor, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, -1, -1));

        daftar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/registrasi mitra.png"))); // NOI18N
        daftar.setContentAreaFilled(false);
        getContentPane().add(daftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 460, -1, -1));

        keluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/logout.png"))); // NOI18N
        keluar.setContentAreaFilled(false);
        getContentPane().add(keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/Halaman Sub Fitur.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void transaktorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transaktorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transaktorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hometransaktor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hometransaktor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hometransaktor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hometransaktor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hometransaktor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton daftar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton keluar;
    private javax.swing.JButton login;
    private javax.swing.JButton transaktor;
    // End of variables declaration//GEN-END:variables
}
