/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;

/**
 *
 * @author Vian
 */
public class homepemilik extends javax.swing.JFrame {

    /**
     * Creates new form homepemilik
     */
    public homepemilik() {
        initComponents();
    }
     public void addtLoginListener(ActionListener listener) {
        login.addActionListener(listener);
    }
  public void pemilik() {
        login.setVisible(false);
    }
  
     public void addtLogoutListener(ActionListener listener) {
        keluar.addActionListener(listener);
    }
    public void addMelihatStok(ActionListener listener){
         melihatstok.addActionListener(listener);
     }
        public void addMelihatLaporanPenjualan(ActionListener listener){
         penjualan.addActionListener(listener);
     }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        penjualan = new javax.swing.JButton();
        melihatstok = new javax.swing.JButton();
        mitra = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        login.setText("masuk");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        keluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/logout.png"))); // NOI18N
        keluar.setContentAreaFilled(false);
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        getContentPane().add(keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        penjualan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/Pemilik Ternak(Laporan Penjjualan).png"))); // NOI18N
        penjualan.setContentAreaFilled(false);
        getContentPane().add(penjualan, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, -1, -1));

        melihatstok.setText("melihat stok");
        melihatstok.setBorderPainted(false);
        melihatstok.setContentAreaFilled(false);
        melihatstok.setOpaque(false);
        melihatstok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                melihatstokActionPerformed(evt);
            }
        });
        getContentPane().add(melihatstok, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 500, 400, 120));

        mitra.setText("melihat mitra");
        getContentPane().add(mitra, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 630, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1410, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keluarActionPerformed

    private void melihatstokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_melihatstokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_melihatstokActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homepemilik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homepemilik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homepemilik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homepemilik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homepemilik().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton keluar;
    private javax.swing.JButton login;
    private javax.swing.JButton melihatstok;
    private javax.swing.JButton mitra;
    private javax.swing.JButton penjualan;
    // End of variables declaration//GEN-END:variables
}
