/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vian
 */
public class pemesanan extends javax.swing.JFrame {

    /**
     * Creates new form pemesanan
     */
    public pemesanan() {
        initComponents();
        tanggal();
    }

    public void addKembaliListener(ActionListener listener) {
        kembali.addActionListener(listener);
    }

    public void tanggal() {
        Thread p = new Thread() {

            public void run() {
                for (;;) {

                    Calendar cal = new GregorianCalendar();
                    int hari = cal.get(Calendar.DAY_OF_MONTH);
                    int bulan = cal.get(Calendar.MONTH);
                    int tahun = cal.get(Calendar.YEAR);
                    tanggal.setText(hari + "/" + (bulan + 1) + "/" + tahun);
                }
            }
        };
        p.start();
    }
//    public void setidMitra(String[] idMitra) {
//        for (String a : idMitra) {
//            this.idmitra.addItem(a);
//        }
//    }

    public void setidMitra(String isi) {
        this.idmitra.setText(isi);
    }

    public void setidStok(String isi) {
        this.idstok.setText(isi);
    }

    public void settanggal(String isi) {
        this.tanggal.setText(isi);
    }

    public void setjumlah(String isi) {
        this.jumlah.setText(isi);
    }

    public void setidPemesanan(String isi) {
        this.idpemesanan.setText(isi);
    }

    public String gettanggal() {
        return tanggal.getText();
    }

    public String getjumlah() {
        return jumlah.getText();
    }

    public String getidMitra() {
        return idmitra.getText();
    }

    public String getidPemesanan() {
        return idpemesanan.getText();
    }

    public String getidStok() {
        return idstok.getText();
    }

    public void popUpPesan(String pesan) {
        JOptionPane.showMessageDialog(this, pesan);
    }

    public int getSelectedRow() {
        return tabel.getSelectedRow();
    }

    public void setTabel(DefaultTableModel tabel) {
        this.tabel.setModel(tabel);
    }

    public String getValueAt(int baris, int kolom) {
        return (String) this.tabel.getValueAt(baris, kolom);
    }

    public void addSaveListener(ActionListener e) {
        this.btnSave.addActionListener(e);
    }

    public void addCancelListener(ActionListener e) {
        this.btnCancel.addActionListener(e);
    }

    public void pilihListener(ActionListener e) {
        this.pilih.addActionListener(e);
    }

    public void message(String pesan) {
        JOptionPane.showMessageDialog(this, pesan);
    }

    public void text(boolean status) {
        this.tanggal.setEnabled(status);
        this.jumlah.setEnabled(status);
        this.idpemesanan.setEnabled(status); //from2
        this.idmitra.setEnabled(status); //from2
        this.idstok.setEnabled(status); //from2
    }

    public void button(boolean status) {
        this.btnSave.setEnabled(status);
        this.btnCancel.setEnabled(status);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jumlah = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        idpemesanan = new javax.swing.JLabel();
        tanggal = new javax.swing.JLabel();
        pilih = new javax.swing.JButton();
        idmitra = new javax.swing.JTextField();
        idstok = new javax.swing.JTextField();
        kembali = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Tittle4", "Tittle5"
            }
        ));
        jScrollPane3.setViewportView(tabel);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 500, 118));

        jLabel3.setText("Banyak Pemesanan");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, -1, -1));

        jLabel1.setText("Id Pemesanan");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, -1, -1));
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 57, 22));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Tanggal Pemesanan");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, -1, -1));

        jumlah.setEnabled(false);
        jumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahActionPerformed(evt);
            }
        });
        getContentPane().add(jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 176, -1));

        jLabel4.setText("Id Mitra");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, -1, -1));

        btnSave.setText("Pesan");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 470, -1, -1));

        jLabel5.setText("Id Produk");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, -1, -1));

        btnCancel.setText("Batal");
        btnCancel.setEnabled(false);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 470, -1, -1));
        getContentPane().add(idpemesanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 57, 22));

        tanggal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 140, 20));

        pilih.setText("Pilih Produk");
        getContentPane().add(pilih, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        idmitra.setEnabled(false);
        getContentPane().add(idmitra, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 170, -1));

        idstok.setEnabled(false);
        getContentPane().add(idstok, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 170, -1));

        kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/kembali.png"))); // NOI18N
        kembali.setContentAreaFilled(false);
        kembali.setFocusPainted(false);
        getContentPane().add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/Pemesanan.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlahActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pemesanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel id;
    private javax.swing.JTextField idmitra;
    private javax.swing.JLabel idpemesanan;
    private javax.swing.JTextField idstok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jumlah;
    private javax.swing.JButton kembali;
    private javax.swing.JButton pilih;
    private javax.swing.JTable tabel;
    private javax.swing.JLabel tanggal;
    // End of variables declaration//GEN-END:variables
}
